
[brick]
name = "Parquet"
type = "library"
version = "0.0.1"
chplVersion = "2.7.0..2.9.0"
license = "None"
source = "https://github.com/ShreyasKhandekar/Parquet"

[dependencies]

[system]
arrow = "19.0.1"
parquet = "19.0.1"


