
[brick]
name = "Parquet"
type = "library"
version = "0.1.0"
chplVersion = "2.8.0"
license = "Apache-2.0"
authors = ["Engin Kayraklioglu", "Shreyas Khandekar", "Ben Harshbarger"]
source = "https://github.com/e-kayrakli/Parquet"

[dependencies]

[system]
arrow = "19.0.1"
parquet = "19.0.1"
